### ISSUE TITLE
Slow speed

### ISSUE THREAD

**Issue by SoftologyPro** [nv-tlabs/LLaMA-Mesh#10]
How fast is this supposed to generate the OBJ vertex points?  I have it installed locally (Windows with a 24GB 4090), the gradio starts, and when I prompt it the vertex generation seems to take around 10 seconds per line/vertex.

Is this normal?  Any tps to speed it up?

Thanks.

**Comment by oursland** [comment]
That's very slow and suspect it is not using your GPU.  On my system (Apple MBP M2 Max with 96 GiB RAM), memory usage at 4096 token context length is 15.16 GiB, which would fit entirely within your 24 GiB 4090.

**Comment by SoftologyPro** [comment]
I did install the appropriate GPU totch and Task Manager shows it is the GPU and not the CPU being used.  Task Manager also shows dedicated GPU memory is 21.9/24.0 so not maxed out there.

For the install I basically use these pip commands to get the requirements, gradio, and then swap CPU torch out for GPU torch.
```
pip install -r requirements.txt
pip install gradio
pip uninstall -y torch
pip install --no-cache-dir --ignore-installed --force-reinstall --no-warn-conflicts torch==2.4.1+cu121 torchvision torchaudio --index-url https://download.pytorch.org/whl/cu121
```

**Comment by SoftologyPro** [comment]
For any other WIndows users (or to help test this issue) here is an install.bat and run.bat.  Save them both to am empty directory, command prompt into that directory, run install.bat, then run run.bat to start it.

install.bat
```
@echo off

echo *** %time% *** Deleting LLaMa-Mesh directory if it exists
if exist LLaMa-Mesh\. rd /S /Q LLaMa-Mesh

echo *** %time% *** Cloning LLaMa-Mesh repository
git clone https://github.com/nv-tlabs/LLaMa-Mesh
cd LLaMa-Mesh

echo *** %time% *** Creating venv
python -m venv venv

echo *** %time% *** Activating venv
call venv\scripts\activate.bat

echo *** %time% *** Installing requirements
python -m pip install --upgrade pip
pip install -r requirements.txt
pip install gradio

echo *** %time% *** Installing GPU torch
pip uninstall -y torch
pip install --no-cache-dir --ignore-installed --force-reinstall --no-warn-conflicts torch==2.4.1+cu121 torchvision torchaudio --index-url https://download.pytorch.org/whl/cu121

call venv\scripts\deactivate.bat
cd ..
echo *** %time% *** Finished LLaMa-Mesh install
echo.
echo Check the stats for any errors.  Do not assume it worked.
pause
```

run.bat
```
@echo off
cd LLaMa-Mesh
call venv\scripts\activate.bat
python app.py
call venv\scripts\deactivate.bat
cd..
```

**Comment by SoftologyPro** [comment]
After well over an hour processing it did finish, but this was the result for "Create a 3D mesh of a ginger and white kitten dancing wearing a tutu"

![image](https://github.com/user-attachments/assets/32092d37-175f-4804-a51b-072caadeead1)

**Comment by SoftologyPro** [comment]
Testing the first example prompt gives this error after clicking it

```
Traceback (most recent call last):
  File "D:\Tests\LLaMA-Mesh\LLaMa-Mesh\venv\lib\site-packages\gradio\queueing.py", line 624, in process_events
    response = await route_utils.call_process_api(
  File "D:\Tests\LLaMA-Mesh\LLaMa-Mesh\venv\lib\site-packages\gradio\route_utils.py", line 323, in call_process_api
    output = await app.get_blocks().process_api(
  File "D:\Tests\LLaMA-Mesh\LLaMa-Mesh\venv\lib\site-packages\gradio\blocks.py", line 2015, in process_api
    result = await self.call_function(
  File "D:\Tests\LLaMA-Mesh\LLaMa-Mesh\venv\lib\site-packages\gradio\blocks.py", line 1574, in call_function
    prediction = await utils.async_iteration(iterator)
  File "D:\Tests\LLaMA-Mesh\LLaMa-Mesh\venv\lib\site-packages\gradio\utils.py", line 710, in async_iteration
    return await anext(iterator)
  File "D:\Tests\LLaMA-Mesh\LLaMa-Mesh\venv\lib\site-packages\gradio\utils.py", line 815, in asyncgen_wrapper
    response = await iterator.__anext__()
  File "D:\Tests\LLaMA-Mesh\LLaMa-Mesh\venv\lib\site-packages\gradio\chat_interface.py", line 678, in _stream_fn
    first_response = await async_iteration(generator)
  File "D:\Tests\LLaMA-Mesh\LLaMa-Mesh\venv\lib\site-packages\gradio\utils.py", line 710, in async_iteration
    return await anext(iterator)
  File "D:\Tests\LLaMA-Mesh\LLaMa-Mesh\venv\lib\site-packages\gradio\utils.py", line 704, in __anext__
    return await anyio.to_thread.run_sync(
  File "D:\Tests\LLaMA-Mesh\LLaMa-Mesh\venv\lib\site-packages\anyio\to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "D:\Tests\LLaMA-Mesh\LLaMa-Mesh\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 2441, in run_sync_in_worker_thread
    return await future
  File "D:\Tests\LLaMA-Mesh\LLaMa-Mesh\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 943, in run
    result = context.run(func, *args)
  File "D:\Tests\LLaMA-Mesh\LLaMa-Mesh\venv\lib\site-packages\gradio\utils.py", line 687, in run_sync_iterator_async
    return next(iterator)
  File "D:\Tests\LLaMA-Mesh\LLaMa-Mesh\app.py", line 158, in chat_llama3_8b
    for text in streamer:
  File "D:\Tests\LLaMA-Mesh\LLaMa-Mesh\venv\lib\site-packages\transformers\generation\streamers.py", line 223, in __next__
    value = self.text_queue.get(timeout=self.timeout)
  File "D:\Python\lib\queue.py", line 179, in get
    raise Empty
_queue.Empty
```

because it does not put the prompt text into the "Type a message" field?

![image](https://github.com/user-attachments/assets/d48431ab-c63c-45ba-a4b6-e89f39ff20d2)

**Comment by oursland** [comment]
There are two fields of pre-written prompts, ones above the entry box and ones below.  The ones above give me an error, but the ones below seem to work.

**Comment by SoftologyPro** [comment]
> There are two fields of pre-written prompts, ones above the entry box and ones below. The ones above give me an error, but the ones below seem to work.

I only see the example buttons and clicked the first of those, ie

![image](https://github.com/user-attachments/assets/11f60e21-3f27-466d-a2d1-ca2f2ac4fc76)

**Comment by giserHacter** [comment]
> How fast is this supposed to generate the OBJ vertex points? I have it installed locally (Windows with a 24GB 4090), the gradio starts, and when I prompt it the vertex generation seems to take around 10 seconds per line/vertex.
> 
> Is this normal? Any tps to speed it up?
> 
> Thanks.

You can try flash attention in pytroch

**Comment by oursland** [comment]
Here's what I see on my machine.

![image](https://github.com/user-attachments/assets/134ae266-6a53-4592-86ac-e833f200f567)

The buttons in the upper box do not seem to work, but the buttons below do.

**Comment by SoftologyPro** [comment]
> Here's what I see on my machine.
> 
> ![image](https://private-user-images.githubusercontent.com/622450/388355984-134ae266-6a53-4592-86ac-e833f200f567.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIxNjczNjksIm5iZiI6MTczMjE2NzA2OSwicGF0aCI6Ii82MjI0NTAvMzg4MzU1OTg0LTEzNGFlMjY2LTZhNTMtNDU5Mi04NmFjLWU4MzNmMjAwZjU2Ny5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEyMVQwNTMxMDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kODVjYzk2NjVlMWY4N2EzZmZjYWJlMTRiYmI0MDI2ZmY5NGU2NTFhNmJkNDdiZWQyMGE2MDg2NWRmNjEwOWE3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.MtFaVKi9K2VDuGJwh1fVlYaFw6vPtqh2VGJGRrNq8HQ)
> 
> The buttons in the upper box ("Gradio ChatInterface") do not seem to work, but the buttons below ("Examples") do.

Anyway, you are on Mac and this has nothing to do with the issue I am trying to get an answer to.  You should start your own issue.

**Comment by SoftologyPro** [comment]
Someone posted then deleted a suggestion to try flash-attn.
Tried that.  Not any faster.  Any other ideas?  Thanks.

**Comment by thuwzy** [comment]
Are you using `bf16`? It's much faster than `fp32`

**Comment by SoftologyPro** [comment]
> Are you using `bf16`? It's much faster than `fp32`

How do I set that?  I do not see either in app.py.

**Comment by jpschw** [comment]
I have the same issue.

I verified my CUDA installation is working:
  print("CUDA available:", torch.cuda.is_available())
  print("CUDA version:", torch.version.cuda)
  print("Device name:", torch.cuda.get_device_name(torch.cuda.current_device()))

Output:
  CUDA available: True
  CUDA version: 12.4
  Device name: NVIDIA GeForce RTX 4070 Ti

I tried changing these lines in app.py to make sure it's using CUDA:
  device = "cuda"
  model = AutoModelForCausalLM.from_pretrained(model_path).to(device)

It still only generates one vertex every ~10 seconds.

**Comment by Kingdroper** [comment]
> Testing the first example prompt gives this error after clicking it
> 
> ```
> Traceback (most recent call last):
>   File "D:\Tests\LLaMA-Mesh\LLaMa-Mesh\venv\lib\site-packages\gradio\queueing.py", line 624, in process_events
>     response = await route_utils.call_process_api(
>   File "D:\Tests\LLaMA-Mesh\LLaMa-Mesh\venv\lib\site-packages\gradio\route_utils.py", line 323, in call_process_api
>     output = await app.get_blocks().process_api(
>   File "D:\Tests\LLaMA-Mesh\LLaMa-Mesh\venv\lib\site-packages\gradio\blocks.py", line 2015, in process_api
>     result = await self.call_function(
>   File "D:\Tests\LLaMA-Mesh\LLaMa-Mesh\venv\lib\site-packages\gradio\blocks.py", line 1574, in call_function
>     prediction = await utils.async_iteration(iterator)
>   File "D:\Tests\LLaMA-Mesh\LLaMa-Mesh\venv\lib\site-packages\gradio\utils.py", line 710, in async_iteration
>     return await anext(iterator)
>   File "D:\Tests\LLaMA-Mesh\LLaMa-Mesh\venv\lib\site-packages\gradio\utils.py", line 815, in asyncgen_wrapper
>     response = await iterator.__anext__()
>   File "D:\Tests\LLaMA-Mesh\LLaMa-Mesh\venv\lib\site-packages\gradio\chat_interface.py", line 678, in _stream_fn
>     first_response = await async_iteration(generator)
>   File "D:\Tests\LLaMA-Mesh\LLaMa-Mesh\venv\lib\site-packages\gradio\utils.py", line 710, in async_iteration
>     return await anext(iterator)
>   File "D:\Tests\LLaMA-Mesh\LLaMa-Mesh\venv\lib\site-packages\gradio\utils.py", line 704, in __anext__
>     return await anyio.to_thread.run_sync(
>   File "D:\Tests\LLaMA-Mesh\LLaMa-Mesh\venv\lib\site-packages\anyio\to_thread.py", line 56, in run_sync
>     return await get_async_backend().run_sync_in_worker_thread(
>   File "D:\Tests\LLaMA-Mesh\LLaMa-Mesh\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 2441, in run_sync_in_worker_thread
>     return await future
>   File "D:\Tests\LLaMA-Mesh\LLaMa-Mesh\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 943, in run
>     result = context.run(func, *args)
>   File "D:\Tests\LLaMA-Mesh\LLaMa-Mesh\venv\lib\site-packages\gradio\utils.py", line 687, in run_sync_iterator_async
>     return next(iterator)
>   File "D:\Tests\LLaMA-Mesh\LLaMa-Mesh\app.py", line 158, in chat_llama3_8b
>     for text in streamer:
>   File "D:\Tests\LLaMA-Mesh\LLaMa-Mesh\venv\lib\site-packages\transformers\generation\streamers.py", line 223, in __next__
>     value = self.text_queue.get(timeout=self.timeout)
>   File "D:\Python\lib\queue.py", line 179, in get
>     raise Empty
> _queue.Empty
> ```
> 
> because it does not put the prompt text into the "Type a message" field?
> 
> ![image](https://private-user-images.githubusercontent.com/47686889/387452191-d48431ab-c63c-45ba-a4b6-e89f39ff20d2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ2NzgzNzcsIm5iZiI6MTczNDY3ODA3NywicGF0aCI6Ii80NzY4Njg4OS8zODc0NTIxOTEtZDQ4NDMxYWItYzYzYy00NWJhLWE0YjYtZTg5ZjM5ZmYyMGQyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjIwVDA3MDExN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVkNjg5OTk3NTllNWEyYzA1NjY2ODM5ZWQ2YTA5NDZmMWQ2MzA0MDM4M2UyMDhlMDBiY2ExOTNiMzI2Yzc5OGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.folX10tG-WbV0JnfygfabsYUKaKG0LL98UdYnaf3qpU)
> 
> If I reload the UI and manually type the prompt "Create a 3D model of a wooden hammer" into the "Type a message" field it does then start without error.

I run on NVIDIA L20 GPUs, it does not work!
