### ISSUE TITLE
Gradio Error: _queue.Empty

### ISSUE THREAD

**Issue by Kingdroper** [nv-tlabs/LLaMA-Mesh#21]
Can't generate anything using the sample prompt：
<img width="1311" alt="截屏2024-12-20 14 49 21" src="https://github.com/user-attachments/assets/ea4ac6b9-ebed-4dac-84bb-13cdb2ca2959" />

**Comment by thuwzy** [comment]
What is the output in command line?

**Comment by luispatriciorf** [comment]
Hello,
Same issue over here:

![Image](https://github.com/user-attachments/assets/2840ccf5-21ff-4e61-a1a8-7ee530f00826)

I got this from the command line:

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
Traceback (most recent call last):
  File "D:\LamaMesh\lamamesh\Lib\site-packages\gradio\queueing.py", line 625, in process_events
    response = await route_utils.call_process_api(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<5 lines>...
    )
    ^
  File "D:\LamaMesh\lamamesh\Lib\site-packages\gradio\route_utils.py", line 322, in call_process_api
    output = await app.get_blocks().process_api(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<11 lines>...
    )
    ^
  File "D:\LamaMesh\lamamesh\Lib\site-packages\gradio\blocks.py", line 2042, in process_api
    result = await self.call_function(
             ^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<8 lines>...
    )
    ^
  File "D:\LamaMesh\lamamesh\Lib\site-packages\gradio\blocks.py", line 1601, in call_function
    prediction = await utils.async_iteration(iterator)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\LamaMesh\lamamesh\Lib\site-packages\gradio\utils.py", line 728, in async_iteration
    return await anext(iterator)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\LamaMesh\lamamesh\Lib\site-packages\gradio\utils.py", line 833, in asyncgen_wrapper
    response = await iterator.__anext__()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\LamaMesh\lamamesh\Lib\site-packages\gradio\chat_interface.py", line 884, in _stream_fn
    first_response = await utils.async_iteration(generator)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\LamaMesh\lamamesh\Lib\site-packages\gradio\utils.py", line 728, in async_iteration
    return await anext(iterator)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\LamaMesh\lamamesh\Lib\site-packages\gradio\utils.py", line 722, in __anext__
    return await anyio.to_thread.run_sync(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        run_sync_iterator_async, self.iterator, limiter=self.limiter
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "D:\LamaMesh\lamamesh\Lib\site-packages\anyio\to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        func, args, abandon_on_cancel=abandon_on_cancel, limiter=limiter
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "D:\LamaMesh\lamamesh\Lib\site-packages\anyio\_backends\_asyncio.py", line 2461, in run_sync_in_worker_thread
    return await future
           ^^^^^^^^^^^^
  File "D:\LamaMesh\lamamesh\Lib\site-packages\anyio\_backends\_asyncio.py", line 962, in run
    result = context.run(func, *args)
  File "D:\LamaMesh\lamamesh\Lib\site-packages\gradio\utils.py", line 705, in run_sync_iterator_async
    return next(iterator)
  File "d:\LamaMesh\LLaMA-Mesh-main\app.py", line 161, in chat_llama3_8b
    for text in streamer:
                ^^^^^^^^
  File "D:\LamaMesh\lamamesh\Lib\site-packages\transformers\generation\streamers.py", line 224, in __next__
    value = self.text_queue.get(timeout=self.timeout)
  File "C:\Python313\Lib\queue.py", line 212, in get
    raise Empty
_queue.Empty
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
Traceback (most recent call last):
  File "D:\LamaMesh\lamamesh\Lib\site-packages\gradio\queueing.py", line 625, in process_events
    response = await route_utils.call_process_api(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<5 lines>...
    )
    ^
  File "D:\LamaMesh\lamamesh\Lib\site-packages\gradio\route_utils.py", line 322, in call_process_api
    output = await app.get_blocks().process_api(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<11 lines>...
    )
    ^
  File "D:\LamaMesh\lamamesh\Lib\site-packages\gradio\blocks.py", line 2042, in process_api
    result = await self.call_function(
             ^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<8 lines>...
    )
    ^
  File "D:\LamaMesh\lamamesh\Lib\site-packages\gradio\blocks.py", line 1601, in call_function
    prediction = await utils.async_iteration(iterator)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\LamaMesh\lamamesh\Lib\site-packages\gradio\utils.py", line 728, in async_iteration
    return await anext(iterator)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\LamaMesh\lamamesh\Lib\site-packages\gradio\utils.py", line 833, in asyncgen_wrapper
    response = await iterator.__anext__()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\LamaMesh\lamamesh\Lib\site-packages\gradio\chat_interface.py", line 884, in _stream_fn
    first_response = await utils.async_iteration(generator)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\LamaMesh\lamamesh\Lib\site-packages\gradio\utils.py", line 728, in async_iteration
    return await anext(iterator)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\LamaMesh\lamamesh\Lib\site-packages\gradio\utils.py", line 722, in __anext__
    return await anyio.to_thread.run_sync(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        run_sync_iterator_async, self.iterator, limiter=self.limiter
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "D:\LamaMesh\lamamesh\Lib\site-packages\anyio\to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        func, args, abandon_on_cancel=abandon_on_cancel, limiter=limiter
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "D:\LamaMesh\lamamesh\Lib\site-packages\anyio\_backends\_asyncio.py", line 2461, in run_sync_in_worker_thread
    return await future
           ^^^^^^^^^^^^
  File "D:\LamaMesh\lamamesh\Lib\site-packages\anyio\_backends\_asyncio.py", line 962, in run
    result = context.run(func, *args)
  File "D:\LamaMesh\lamamesh\Lib\site-packages\gradio\utils.py", line 705, in run_sync_iterator_async
    return next(iterator)
  File "d:\LamaMesh\LLaMA-Mesh-main\app.py", line 161, in chat_llama3_8b
    for text in streamer:
                ^^^^^^^^
  File "D:\LamaMesh\lamamesh\Lib\site-packages\transformers\generation\streamers.py", line 224, in __next__
    value = self.text_queue.get(timeout=self.timeout)
  File "C:\Python313\Lib\queue.py", line 212, in get
    raise Empty
_queue.Empty
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
Traceback (most recent call last):
  File "D:\LamaMesh\lamamesh\Lib\site-packages\gradio\queueing.py", line 625, in process_events
    response = await route_utils.call_process_api(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<5 lines>...
    )
    ^
  File "D:\LamaMesh\lamamesh\Lib\site-packages\gradio\route_utils.py", line 322, in call_process_api
    output = await app.get_blocks().process_api(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<11 lines>...
    )
    ^
  File "D:\LamaMesh\lamamesh\Lib\site-packages\gradio\blocks.py", line 2042, in process_api
    result = await self.call_function(
             ^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<8 lines>...
    )
    ^
  File "D:\LamaMesh\lamamesh\Lib\site-packages\gradio\blocks.py", line 1601, in call_function
    prediction = await utils.async_iteration(iterator)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\LamaMesh\lamamesh\Lib\site-packages\gradio\utils.py", line 728, in async_iteration
    return await anext(iterator)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\LamaMesh\lamamesh\Lib\site-packages\gradio\utils.py", line 833, in asyncgen_wrapper
    response = await iterator.__anext__()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\LamaMesh\lamamesh\Lib\site-packages\gradio\chat_interface.py", line 884, in _stream_fn
    first_response = await utils.async_iteration(generator)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\LamaMesh\lamamesh\Lib\site-packages\gradio\utils.py", line 728, in async_iteration
    return await anext(iterator)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\LamaMesh\lamamesh\Lib\site-packages\gradio\utils.py", line 722, in __anext__
    return await anyio.to_thread.run_sync(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        run_sync_iterator_async, self.iterator, limiter=self.limiter
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "D:\LamaMesh\lamamesh\Lib\site-packages\anyio\to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        func, args, abandon_on_cancel=abandon_on_cancel, limiter=limiter
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "D:\LamaMesh\lamamesh\Lib\site-packages\anyio\_backends\_asyncio.py", line 2461, in run_sync_in_worker_thread
    return await future
           ^^^^^^^^^^^^
  File "D:\LamaMesh\lamamesh\Lib\site-packages\anyio\_backends\_asyncio.py", line 962, in run
    result = context.run(func, *args)
  File "D:\LamaMesh\lamamesh\Lib\site-packages\gradio\utils.py", line 705, in run_sync_iterator_async
    return next(iterator)
  File "d:\LamaMesh\LLaMA-Mesh-main\app.py", line 161, in chat_llama3_8b
    for text in streamer:
                ^^^^^^^^
  File "D:\LamaMesh\lamamesh\Lib\site-packages\transformers\generation\streamers.py", line 224, in __next__
    value = self.text_queue.get(timeout=self.timeout)
  File "C:\Python313\Lib\queue.py", line 212, in get
    raise Empty
_queue.Empty

**Comment by Brian-Castle** [comment]
I get this same error, and the same thing occurs on HuggingFace.

**Comment by Brian-Castle** [comment]
The public demo on HuggingFace does the same thing. It simply says "Error" with no further explanation, but the result is the same (no output).
